#!/usr/bin/env python3
from __future__ import annotations

import base64
import hashlib
import io
import tarfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "cloud" / "src" / "agent_bundle.js"
INCLUDE = [
    "pyproject.toml",
    "README.md",
]
INCLUDE += [str(p.relative_to(ROOT)) for p in sorted((ROOT / "wx2codex_agent").glob("*.py"))]


def main() -> None:
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        for rel in INCLUDE:
            path = ROOT / rel
            if not path.exists():
                raise FileNotFoundError(path)
            data = path.read_bytes()
            info = tarfile.TarInfo(name=rel)
            info.size = len(data)
            info.mode = 0o644
            info.mtime = 0
            tar.addfile(info, io.BytesIO(data))
    blob = buf.getvalue()
    encoded = base64.b64encode(blob).decode("ascii")
    sha = hashlib.sha256(blob).hexdigest()
    OUT.write_text(
        "// Auto-generated by scripts/build-agent-bundle.py. Do not edit by hand.\n"
        f"export const AGENT_BUNDLE_VERSION = '0.1.0';\n"
        f"export const AGENT_BUNDLE_SHA256 = '{sha}';\n"
        f"export const AGENT_BUNDLE_BASE64 = '{encoded}';\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({len(blob)} bytes, sha256={sha})")


if __name__ == "__main__":
    main()
